version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-flask
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/twitter_db
    ports:
      - "8000:8000"
    volumes:
      - ./dist:/app/dist
    depends_on:
      - db
    networks:
      - backend
    command: ["python", "backend/main.py"]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./dist:/app/dist

    depends_on:
      - backend
    networks:
      - backend

  db:
    image: postgres:17
    container_name: backend_postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
